declare module '@aztlan/bem' {
  export const base: string;
  export const elementContent: string;
  export const elementHeading: string;
  export const elementItem: string;
  export const elementList: string;
  export const elementNavigation: string;
  export const elementSection: string;
  export const elementSubtitle: string;
  export const modifierActive: string;
  export const modifierAnimated: string;
  export const modifierAttached: string;
  export const modifierBlur: string;
  export const modifierClear: string;
  export const modifierCompact: string;
  export const modifierError: string;
  export const modifierGhost: string;
  export const modifierGradient: string;
  export const modifierImage: string;
  export const modifierNext: string;
  export const modifierOpen: string;
  export const modifierPrevious: string;
  export const modifierSimple: string;
  export const modifierSpaced: string;
  export const modifierUnderlined: string;
  export const wrapperGroup: string;
}
