module.exports = {
  elementContent: "content",
  elementHeading: "heading",
  elementItem: "item",
  elementList: "list",
  elementNavigation: "navigation",
  elementSection: "section",
  elementSubtitle: "subtitle",
  modifierActive: "active",
  modifierAnimated: "animated",
  modifierAttached: "attached",
  modifierBlur: "blur",
  modifierClear: "clear",
  modifierCompact: "compact",
  modifierError: "error",
  modifierGhost: "ghost",
  modifierGradient: "gradient",
  modifierImage: "image",
  modifierFixed: "fixed",
  modifierNext: "next",
  modifierOpen: "open",
  modifierPrevious: "previous",
  modifierSimple: "simple",
  modifierSpaced: "spaced",
  modifierUnderlined: "underlined",
  wrapperGroup: "group",
  base: "ui",
};
