name: publish-to-npm
on:
  push:
    tags:
      - v*

jobs:
  publish:
    if: startsWith(github.event.head_commit.message, 'auto-publish')
    runs-on: ubuntu-latest

    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: setup .npmrc it uses NODE_AUTH_TOKEN
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"

      - name: Configure CI Git User
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

      - name: Check if able to publish changes
        run: |
          npm whoami

      - name: Install dependencies                            
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: |
          npm install

      - name: Test
        run: npm test

      - id: cache-modules
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Publish
        run: |
          lerna publish from-package --yes
